[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS="--prefix=/dev/null"
[build]
  publish = "public"
  command = "npx pnpm i --store=node_modules/.pnpm-store &&  || { cat /opt/buildhome/.npm/_logs/* ; sleep 30 ; false; }"